add_library(xrRender_VK)

target_sources(xrRender_VK PRIVATE
    stdafx.cpp
    stdafx.h
    xrRender_VK.cpp
    vk_test_hw.cpp
    vk_rendertarget.h
    vk_rendertarget.cpp

    vkr_shaders.cpp
    ../xrRenderVK/CommonTypes.h
    ../xrRenderVK/vkHW.h
    ../xrRenderVK/vkHW.cpp
    ../xrRenderVK/vkHWCaps.h
    ../xrRenderVK/vkHWCaps.cpp
    ../xrRenderVK/vkState.h
    ../xrRenderVK/vkState.cpp
    ../xrRenderVK/vkR_Backend_Runtime.h
    ../xrRenderVK/vkBlender_Recorder.cpp
    ../xrRenderVK/vkBufferUtils.cpp
    ../xrRenderVK/vkResourceManager_Resources.cpp
    ../xrRenderVK/vkResourceManager_Scripting.cpp
    ../xrRenderVK/vkTexture.cpp
    ../xrRenderVK/vkSH_Texture.cpp
    ../xrRenderVK/vkSH_RT.cpp
    ../xrRenderVK/vkDetailManager_VS.cpp
    ../xrRenderVK/vkr_screenshot.cpp

    ../xrRender/Animation.cpp
    ../xrRender/Animation.h
    ../xrRender/AnimationKeyCalculate.h
    ../xrRender/Blender_CLSID.h
    ../xrRender/Blender.cpp
    ../xrRender/Blender.h
    ../xrRender/Blender_Recorder.cpp
    ../xrRender/Blender_Recorder.h
    ../xrRender/Blender_Recorder_R2.cpp
    ../xrRender/Blender_Recorder_StandartBinding.cpp
    ../xrRender/BufferUtils.h
    ../xrRender/ColorMapManager.cpp
    ../xrRender/ColorMapManager.h
    ../xrRender/D3DUtils.cpp
    ../xrRender/D3DUtils.h
    ../xrRender/D3DXRenderBase.cpp
    ../xrRender/D3DXRenderBase.h
    ../xrRender/DetailFormat.h
    ../xrRender/DetailManager_CACHE.cpp
    ../xrRender/DetailManager.cpp
    ../xrRender/DetailManager_Decompress.cpp
    ../xrRender/DetailManager_soft.cpp
    ../xrRender/DetailManager.h
    ../xrRender/DetailManager_VS.cpp
    ../xrRender/DetailModel.cpp
    ../xrRender/DetailModel.h
    ../xrRender/du_box.cpp
    ../xrRender/du_box.h
    ../xrRender/du_cone.cpp
    ../xrRender/du_cone.h
    ../xrRender/du_cylinder.cpp
    ../xrRender/du_cylinder.h
    ../xrRender/du_sphere.cpp
    ../xrRender/du_sphere.h
    ../xrRender/du_sphere_part.cpp
    ../xrRender/du_sphere_part.h
    ../xrRender/dxDebugRender.cpp
    ../xrRender/dxDebugRender.h
    ../xrRender/dxEnvironmentRender.cpp
    ../xrRender/dxEnvironmentRender.h
    ../xrRender/dxFontRender.cpp
    ../xrRender/dxFontRender.h
    ../xrRender/dxImGuiRender.cpp
    ../xrRender/dxImGuiRender.h
    ../xrRender/dxLensFlareRender.cpp
    ../xrRender/dxLensFlareRender.h
    ../xrRender/dxObjectSpaceRender.cpp
    ../xrRender/dxObjectSpaceRender.h
    ../xrRender/dxParticleCustom.cpp
    ../xrRender/dxParticleCustom.h
    ../xrRender/dxRainRender.cpp
    ../xrRender/dxRainRender.h
    ../xrRender/dxRenderFactory.cpp
    ../xrRender/dxRenderFactory.h
    ../xrRender/dxStatGraphRender.cpp
    ../xrRender/dxStatGraphRender.h
    ../xrRender/dxThunderboltDescRender.cpp
    ../xrRender/dxThunderboltDescRender.h
    ../xrRender/dxThunderboltRender.cpp
    ../xrRender/dxThunderboltRender.h
    ../xrRender/dxUIRender.cpp
    ../xrRender/dxUIRender.h
    ../xrRender/dxUISequenceVideoItem.cpp
    ../xrRender/dxUISequenceVideoItem.h
    ../xrRender/dxUIShader.cpp
    ../xrRender/dxUIShader.h
    ../xrRender/dxWallMarkArray.cpp
    ../xrRender/dxWallMarkArray.h
    ../xrRender/ETextureParams.cpp
    ../xrRender/ETextureParams.h
    ../xrRender/FBasicVisual.cpp
    ../xrRender/FBasicVisual.h
    ../xrRender/FHierrarhyVisual.cpp
    ../xrRender/FHierrarhyVisual.h
    ../xrRender/FLOD.cpp
    ../xrRender/FLOD.h
    ../xrRender/FProgressive.cpp
    ../xrRender/FProgressive.h
    ../xrRender/FSkinned.cpp
    ../xrRender/FSkinned.h
    ../xrRender/FSkinnedTypes.h
    ../xrRender/FTreeVisual.cpp
    ../xrRender/FTreeVisual.h
    ../xrRender/FVF.h
    ../xrRender/FVisual.cpp
    ../xrRender/FVisual.h
    ../xrRender/HOM.cpp
    ../xrRender/HOM.h
    ../xrRender/HWCaps.h
    ../xrRender/IRenderDetailModel.h
    ../xrRender/KinematicAnimatedDefs.h
    ../xrRender/KinematicsAddBoneTransform.hpp
    ../xrRender/light.cpp
    ../xrRender/Light_DB.cpp
    ../xrRender/Light_DB.h
    ../xrRender/light_gi.cpp
    ../xrRender/light_gi.h
    ../xrRender/light.h
    ../xrRender/Light_Package.cpp
    ../xrRender/Light_Package.h
    ../xrRender/Light_Render_Direct_ComputeXFS.cpp
    ../xrRender/Light_Render_Direct.cpp
    ../xrRender/Light_Render_Direct.h
    ../xrRender/light_smapvis.cpp
    ../xrRender/light_smapvis.h
    ../xrRender/LightTrack.cpp
    ../xrRender/LightTrack.h
    ../xrRender/light_vis.cpp
    ../xrRender/ModelPool.cpp
    ../xrRender/ModelPool.h
    ../xrRender/NvTriStrip.cpp
    ../xrRender/NvTriStrip.h
    ../xrRender/NvTriStripObjects.cpp
    ../xrRender/NvTriStripObjects.h
    ../xrRender/occRasterizer_core.cpp
    ../xrRender/occRasterizer.cpp
    ../xrRender/occRasterizer.h
    ../xrRender/ParticleEffect.cpp
    ../xrRender/ParticleEffectDef.cpp
    ../xrRender/ParticleEffectDef.h
    ../xrRender/ParticleEffect.h
    ../xrRender/ParticleGroup.cpp
    ../xrRender/ParticleGroup.h
    ../xrRender/PSLibrary.cpp
    ../xrRender/PSLibrary.h
    ../xrRender/QueryHelper.h
    ../xrRender/R_Backend.cpp
    ../xrRender/R_Backend_DBG.cpp
    ../xrRender/R_Backend.h
    ../xrRender/R_Backend_hemi.cpp
    ../xrRender/R_Backend_hemi.h
    ../xrRender/R_Backend_Runtime.cpp
    ../xrRender/R_Backend_tree.cpp
    ../xrRender/R_Backend_tree.h
    ../xrRender/R_Backend_xform.cpp
    ../xrRender/R_Backend_xform.h
    ../xrRender/r_constants_cache.h
    ../xrRender/r_constants.cpp
    ../xrRender/r_constants.h
    ../xrRender/r__dsgraph_build.cpp
    ../xrRender/r__dsgraph_render.cpp
    ../xrRender/r__dsgraph_render_lods.cpp
    ../xrRender/r__dsgraph_types.h
    ../xrRender/R_DStreams.cpp
    ../xrRender/R_DStreams.h
    ../xrRender/ResourceManager.cpp
    ../xrRender/ResourceManager.h
    ../xrRender/ResourceManager_Loader.cpp
    ../xrRender/ResourceManager_Reset.cpp
    ../xrRender/ResourceManager_Resources.cpp
    ../xrRender/r__occlusion.cpp
    ../xrRender/r__occlusion.h
    ../xrRender/r__pixel_calculator.cpp
    ../xrRender/r__pixel_calculator.h
    ../xrRender/r__sector.cpp
    ../xrRender/r__sector.h
    ../xrRender/r__sector_detect.cpp
    ../xrRender/r__sector_traversal.cpp
    ../xrRender/r_sun_cascades.h
    ../xrRender/r__sync_point.cpp
    ../xrRender/r__sync_point.h
    ../xrRender/Shader.cpp
    ../xrRender/Shader.h
    ../xrRender/ShaderResourceTraits.h
    ../xrRender/SH_Atomic.cpp
    ../xrRender/SH_Atomic.h
    ../xrRender/SH_Constant.cpp
    ../xrRender/SH_Constant.h
    ../xrRender/SH_Matrix.cpp
    ../xrRender/SH_Matrix.h
    ../xrRender/SH_RT.h
    ../xrRender/SH_Texture.h
    ../xrRender/SkeletonAnimated.cpp
    ../xrRender/SkeletonAnimated.h
    ../xrRender/SkeletonCustom.cpp
    ../xrRender/SkeletonCustom.h
    ../xrRender/SkeletonRigid.cpp
    ../xrRender/SkeletonX.cpp
    ../xrRender/SkeletonX.h
    ../xrRender/SkeletonXSkinXW.h
    ../xrRender/SkeletonXSkinXW_CPP.cpp
    ../xrRender/SkeletonXSkinXW_SSE.cpp
    ../xrRender/SkeletonXVertRender.h
    ../xrRender/TextureDescrManager.cpp
    ../xrRender/TextureDescrManager.h
    ../xrRender/tss_def.cpp
    ../xrRender/tss_def.h
    ../xrRender/tss.h
    ../xrRender/VertexCache.cpp
    ../xrRender/VertexCache.h
    ../xrRender/WallmarksEngine.cpp
    ../xrRender/WallmarksEngine.h
    ../xrRender/xr_effgamma.cpp
    ../xrRender/xr_effgamma.h
    ../xrRender/xrRender_console.cpp
    ../xrRender/xrRender_console.h
    ../xrRender/xrStripify.cpp
    ../xrRender/xrStripify.h
    ../xrRender/blenders/blender_bloom_build.cpp
    ../xrRender/blenders/blender_bloom_build.h
    ../xrRender/blenders/Blender_BmmD_deferred.cpp
    ../xrRender/blenders/blender_combine.cpp
    ../xrRender/blenders/blender_combine.h
    ../xrRender/blenders/blender_deffer_aref.cpp
    ../xrRender/blenders/blender_deffer_aref.h
    ../xrRender/blenders/blender_deffer_flat.cpp
    ../xrRender/blenders/blender_deffer_flat.h
    ../xrRender/blenders/blender_deffer_model.cpp
    ../xrRender/blenders/blender_deffer_model.h
    ../xrRender/blenders/Blender_detail_still_deferred.cpp
    ../xrRender/blenders/Blender_Editor_Selection.cpp
    ../xrRender/blenders/Blender_Editor_Selection.h
    ../xrRender/blenders/Blender_Editor_Wire.cpp
    ../xrRender/blenders/Blender_Editor_Wire.h
    ../xrRender/blenders/blender_light_direct_cascade.cpp
    ../xrRender/blenders/blender_light_direct_cascade.h
    ../xrRender/blenders/blender_light_direct.cpp
    ../xrRender/blenders/blender_light_direct.h
    ../xrRender/blenders/blender_light_mask.cpp
    ../xrRender/blenders/blender_light_mask.h
    ../xrRender/blenders/blender_light_occq.cpp
    ../xrRender/blenders/blender_light_occq.h
    ../xrRender/blenders/blender_light_point.cpp
    ../xrRender/blenders/blender_light_point.h
    ../xrRender/blenders/blender_light_reflected.cpp
    ../xrRender/blenders/blender_light_reflected.h
    ../xrRender/blenders/blender_light_spot.cpp
    ../xrRender/blenders/blender_light_spot.h
    "../xrRender/blenders/Blender_Lm(EbB).cpp"
    ../xrRender/blenders/blender_luminance.cpp
    ../xrRender/blenders/blender_luminance.h
    ../xrRender/blenders/Blender_Model_EbB_deferred.cpp
    ../xrRender/blenders/Blender_Particle_deferred.cpp
    ../xrRender/blenders/Blender_Screen_SET.cpp
    ../xrRender/blenders/Blender_Screen_SET.h
    ../xrRender/blenders/blender_ssao.cpp
    ../xrRender/blenders/blender_ssao.h
    ../xrRender/blenders/Blender_tree_deferred.cpp
    ../xrRender/blenders/uber_deffer.cpp

    r2_R_sun.cpp
    ../xrRender_R2/r2.cpp
    ../xrRender_R2/r2.h
    ../xrRender_R2/r2_blenders.cpp
    ../xrRender_R2/r2_loader.cpp
    ../xrRender_R2/r2_R_calculate.cpp
    ../xrRender_R2/r2_R_lights.cpp
    ../xrRender_R2/r2_R_render.cpp
    ../xrRender_R2/r2_types.h
    ../xrRender_R2/r3_R_rain.cpp
    ../xrRender_R2/render_phase_sun.cpp
    ../xrRender_R2/SMAP_Allocator.h
)

target_include_directories(xrRender_VK
    PRIVATE
    "${CMAKE_CURRENT_SOURCE_DIR}"
    "${CMAKE_SOURCE_DIR}/src"
    "${CMAKE_SOURCE_DIR}/src/Layers/xrRender"
    "${CMAKE_SOURCE_DIR}/src/Include/xrRender"
    "${CMAKE_SOURCE_DIR}/src/Layers/xrRender_R2"
    "${CMAKE_SOURCE_DIR}/src/Layers/xrRenderVK"
    "${CMAKE_SOURCE_DIR}/sdk/include"
    "${CMAKE_SOURCE_DIR}/sdk/include/DirectXMesh"
    "${CMAKE_SOURCE_DIR}/Externals"
    "${CMAKE_SOURCE_DIR}/Externals/gli"
    "${CMAKE_SOURCE_DIR}/Externals/gli/external"
)

target_link_libraries(xrRender_VK
    PRIVATE
    xrAPI
    xrCDB
    xrCore
    xrEngine
    xrMaterialSystem
    xrParticles
    xrScriptEngine
    xrImGui
    $<$<BOOL:${ANDROID}>:vulkan log SDL2::SDL2>
)

target_compile_definitions(xrRender_VK
    PRIVATE
    XRRENDER_VK_EXPORTS
    USE_VK
    RENDER_NAMESPACE=render_vk
    PURE_DYNAMIC_CAST
)

set_target_properties(xrRender_VK PROPERTIES
    PREFIX ""
)

target_precompile_headers(xrRender_VK
    PRIVATE
    $<$<COMPILE_LANGUAGE:CXX>:stdafx.h>
)

if (BUILD_SHARED_LIBS)
    install(TARGETS xrRender_VK LIBRARY
        DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    )
endif()
